# Configuration names
CONFIGURATION_FILE = "config.json"

CONFIGURATION_RUN_CONFIG = "runConfig"
CONFIGURATION_RUN_BLINK_TIME_COLON = "blinkTimeColon"
CONFIGURATION_RUN_TEMP = "temp"
CONFIGURATION_RUN_CLOCK_TYPE = "clockType"
CONFIGURATION_RUN_SHOW_TEMP = "showTemp"
CONFIGURATION_RUN_AUTOLIGHT = "autolight"

CONFIGURATION_WIFI_CONFIG = "wifiConfig"
CONFIGURATION_WIFI_ENABLED = "enabled"
CONFIGURATION_WIFI_HOSTNAME = "hostname"
CONFIGURATION_WIFI_SSID = "ssid"
CONFIGURATION_WIFI_PASSPHRASE = "passphrase"
CONFIGURATION_WIFI_NTP_ENABLED = "ntpEnabled"
CONFIGURATION_WIFI_NTP_PTZ = "ntpPTZ"

CONFIGURATION_MQTT_CONFIG = "mqttConfig"
CONFIGURATION_MQTT_ENABLED = "enabled"
CONFIGURATION_MQTT_BROKER = "broker"
CONFIGURATION_MQTT_PREFIX = "prefix"

# Scheduler name callbacks
SCHEDULER_BUTTON_PRESS = "button-press"

SCHEDULER_CLOCK_SECOND = "clock-second"

SCHEDULER_ENABLE_LEDS = "enable-leds"
SCHEDULER_ANIMATION = "animation"
SCHEDULER_UPDATE_BACKLIGHT_VALUE = "update_auto_backlight_value"

SCHEDULER_MQTT_HEARTBEAT = "mqtt-heartbeat"
SCHEDULER_MQTT_CHECK = "mqtt-check"
SCHEDULER_MQTT_STATE = "mqtt-state"

SCHEDULER_POMODORO_SECOND = "pomodoro-second"

SCHEDULER_SPEAKER_BEEPS = "speaker-beeps"

SCHEDULER_TIME_SET_HALF_SECOND = "time-set-half-second"
SCHEDULER_TIME_SET_MINUTE = "time-set-minute"


# App names
APP_CLOCK = "CLOCK"
APP_POMODORO = "POMODORO"
APP_TIME_SET = "TIME SET"
