#!/usr/bin/env python3
import time
import network
import upip
from configuration import wlan_id, wlan_password

print("Connecting to wifi")
wlan = network.WLAN(network.STA_IF)
wlan.active(True)
wlan.config(pm=0xa11140)  # Disable powersave mode
wlan.connect(wlan_id, wlan_password)

# Wait for connect or fail
max_wait = 10
while max_wait > 0:
    if wlan.status() < 0 or wlan.status() >= 3:
        break
    max_wait -= 1
    print('Waiting for connection...')
    time.sleep(1)

print("Installing umqtt.simple")
upip.install('umqtt.simple')
